name: Deploy to GitHub Pages

on:
  # Ejecutar en cada push al branch principal
  push:
    branches: [ main ]
  # Permite ejecutar manualmente desde la pestaña Actions
  workflow_dispatch:

# Configuración de permisos
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          PUBLIC_BASE_URL: /Portafolio-Diego-G

      # Preparar archivos para el despliegue
      - name: Prepare files for deployment
        run: |
          # Archivo .nojekyll para evitar el procesamiento Jekyll
          touch dist/.nojekyll
          
          # Copiar el archivo 404.html personalizado
          cp public/404.html dist/404.html
          
          # Crear un archivo para verificar la URL base
          echo "Base URL: /Portafolio-Diego-G" > dist/site-info.txt
          
          # Copiar el archivo 404.html a la raíz para mejor compatibilidad
          cp dist/404.html dist/index.html.404
          
      # Verificar estructura de la carpeta dist
      - name: List dist directory
        run: ls -la dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true # Limpia el branch de destino antes de desplegar
          single-commit: true # Un solo commit en el branch 