name: Deploy to GitHub Pages

on:
  # Ejecutar en cada push al branch principal
  push:
    branches: [ main ]
  # Permite ejecutar manualmente desde la pestaña Actions
  workflow_dispatch:

# Permitir que este job clone el repositorio y cree un despliegue en GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build with Astro
        run: npm run build

      # Crea el archivo .nojekyll para evitar el procesamiento de Jekyll
      - name: Create .nojekyll file
        run: touch ./dist/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 